In [2]:
import torch

In [3]:
t1 = torch.tensor(4.)
t1.dtype

torch.float32

In [4]:
# Vector
t2 = torch.tensor([1.,2,3,4,5.])
t2

tensor([1., 2., 3., 4., 5.])

In [5]:
# Matrix
t3 = torch.tensor([[1,3],[2.,5.],[1,5]])
t3

tensor([[1., 3.],
        [2., 5.],
        [1., 5.]])

In [6]:
# Multi Dimensional Array
# t4 = torch.tensor([[1.,2,3],[4,5,6],[5,7]])   Is not correct instead

t4 = torch.tensor([[1.,2,3],[4,5,6],[5,7,8]])
t4

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [5., 7., 8.]])

The main difference of list of list and a multidimensional array is that, in list of list we can have a list of different sizes but the same is not possible with tensors.

In [7]:
print("t1 :- ",t1.shape,"t2 :- ",t2.shape,"t3 :- ",t3.shape,"t4 :- ",t4.shape,)

t1 :-  torch.Size([]) t2 :-  torch.Size([5]) t3 :-  torch.Size([3, 2]) t4 :-  torch.Size([3, 3])


In [26]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(1.,requires_grad=True)

In [28]:
y = w*x + b
#y.backward()
y

tensor(13., grad_fn=<AddBackward0>)

In [29]:
y.backward()

Gradients/Derivates

In [30]:
print('dy/dx :- ',x.grad)
print('dy/dw :- ',w.grad)
print('dy/db :- ',b.grad)

dy/dx :-  None
dy/dw :-  tensor(3.)
dy/db :-  tensor(1.)


In [11]:
import numpy as np

x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

Numpy to tensor

In [12]:
y = torch.from_numpy(x)
print(y)
x.dtype, y.dtype

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


(dtype('int32'), torch.int32)

Tensor to numpy

In [13]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])